### ISSUE TITLE
TrustedGRUB2 crashes with more than five submenu entries

### ISSUE THREAD

**Issue by ts468** [Sirrix-AG/TrustedGRUB2#10]
It seems as TrustedGRUB2 is constantly rebooting if there are more than five submenu entries in grub.cfg. The grub.cfg that triggers the rebooting is https://gist.github.com/anonymous/07fe464370636e3b4b69 . Could anyone maybe confirm that issue? And, in case it is reproducible, how could it be fixed?

Update: It seems as the number of submenu entries that TrustedGRUB2 is working with depends on the path length of the linux, initrd, systemConfig or init entries.

**Comment by neusdan** [comment]
I will probably find next week time to investigate this. Thanks for reporting.

**Comment by ts468** [comment]
@neusdan, thanks for going to have a look!

**Comment by neusdan** [comment]
Sorry for the delay. I tried your grub.cfg and for me it's working with the latest master code.

If you're still using TrustedGRUB2 can you retry if you still have this problem?
