### ISSUE TITLE
UEFI feature

### ISSUE THREAD

**Issue by chava33** [Sirrix-AG/TrustedGRUB2#15]
I am not sure, where to ask a question, so just put it in the issue section..  Sorry

Thanks for the great work. Is there any work going on in enabling UEFI support or any estimated time?

**Comment by neusdan** [comment]
I won't have time this year working on this. But maybe someone contributes it?!

**Comment by seehwan** [comment]
I have strong interest on this subject. Could I join this work?
I have written some code, that actually works with my toy machine.
BTW. UEFI already have secureboot; do we need redundant implementation of boot measurement with TPM? Or can we say that they are complementary?

**Comment by neusdan** [comment]
It would be nice if you could help with implementing UEFI support. Feel free to open some pull requests. I would prefer small incremental steps that are easy to review.

FYI: Matthew Garret has already implemented UEFI TPM support for GRUB2 here: 
https://github.com/mjg59/grub

Trusted boot and secure boot are probably redundant if only used to secure the boot process. But if you want for example to do remote attestation you still need the measured boot.

**Comment by securitykernel** [comment]
Unfortunately, this project is deprecated and no longer maintained. I will be closing this issue.
