### ISSUE TITLE
Is TrustedGRUB 2 reproducible?

### ISSUE THREAD

**Issue by cristianberneanu** [Sirrix-AG/TrustedGRUB2#21]
Hello,

First of all, thank you for making this project!

I would like to know if building TrustedGRUB 2 from the same source archive would lead to the same output binaries each time and, in consequence, to the same measurements in the TPM.

**Comment by cristianberneanu** [comment]
Sorry, I submitted too soon, I updated the issue with a more explicit question.

**Comment by neusdan** [comment]
Hi,

good question. I've never been tested.

**Comment by cristianberneanu** [comment]
I just did a quick test and got back identical hashes for *.img and *.mod files after building the project twice on the same machine.
