### ISSUE TITLE
Split up PCR 10 measurement

### ISSUE THREAD

**Issue by neusdan** [Sirrix-AG/TrustedGRUB2#34]
Currently PCR 10 is used for grub2-modules, Linux-kernel, initrd, ntldr, etc.

I wan't to have grub2 measurements seperated from other usecase specific measurements.

The goal is to use PCR 10 for grub2-modules, fonts, locales etc. and some other PCR for initrd, kernel etc.

**Comment by insecure** [comment]
Do you mind using PCR10 for kernel/initrd and some other PCR for the rest? This seems more compatible with already existing installations. You'll usually build grub modules into the core.img (and do not use fonts, etc. at all ;-)).

**Comment by neusdan** [comment]
Good point. I'll choose some other PCR value for the grub2 measurements.
