### ISSUE TITLE
Multiboot files not measured

### ISSUE THREAD

**Issue by mtahmed** [Sirrix-AG/TrustedGRUB2#35]
Kernels loaded using the `multiboot` command don't seem to be measured. E.g. a typical Xen menuentry looks like this:

```
menuentry 'Xen with Linux 3.2 ...' {
  ...
  multiboot /xen.gz placeholder ${xen_rm_opts}
  module /vmlinuz-3.2 placeholder root=/dev/sda1 ...
  module --nounzip /initramfs-3.2.img
  ...
}
```

In this case, the files `xen.gz`, `vliminux-3.2`, `initramfs-3.2.img` need to be measured but aren't. The command functions are defined in `grub-core/loader/i386/xen.c`.

The change seems simple enough if I don't follow the new convention of measuring the same buffer that is loaded into memory. Would you be able to pick this up or would you rather I work on it?

**Comment by neusdan** [comment]
Thanks for reporting. I'll look into this the next days.

**Comment by neusdan** [comment]
Could you upload those files or tell me a location where i can download some multiboot files for testing?

**Comment by mtahmed** [comment]
If you install Xen on your distribution, it will provide those files and install the relevant grub menu entries. I have also attached the `xen.gz` for use with the multiboot commands and whatever the local kernel/initrd are can be used for `module`
 commands.

[xen.gz](https://github.com/Sirrix-AG/TrustedGRUB2/files/81635/xen.gz)

**Comment by neusdan** [comment]
Could you try the implementation from PR #37 ?

**Comment by mtahmed** [comment]
Tried and it works as expected. Thanks a lot for doing this!
