### ISSUE TITLE
Tested TPM modules/IC

### ISSUE THREAD

**Issue by ronaldonunez** [Sirrix-AG/TrustedGRUB2#43]
What is the list of TPM modules/IC compatible with the TrustedGRUB2? I successfully tested it with Infineon TPM IC (present in most of TPM modules). I would like to know if Nuvoton NPCT620A TPM IC also compatible with it?

**Comment by neusdan** [comment]
There is no such list. Unfortunately i can't tell if this TPM is supported or not because i have no such TPM here.

**Comment by zaolin** [comment]
The TrustedGrub 2 uses the firmware interface to call the TPM. Normally all TPM's supported by the firmware itself should work!

**Comment by zaolin** [comment]
It can happen that some commands are incompatible with TPM itself but if so something is wrong on the TPM side. TrustedGrub 2 only supports TPM v1.2 devices. The TPM you posted is not listed on the company homepage ?!

**Comment by ronaldonunez** [comment]
Thanks for your answers. I was not able to find any information about NPCT 620A on Nuvoton web site. Based on what I found here: http://permalink.gmane.org/gmane.comp.encryption.tpmdd.devel/1198  I can believe that the NPCT6xx is a TPM2.0 IC, which is not supported by TrustedGrub2.
