### ISSUE TITLE
TrustedGRUB2 fails to boot with TPM 1.2 on a HP desktop

### ISSUE THREAD

**Issue by amitlimaye** [Sirrix-AG/TrustedGRUB2#45]
Hello i compiled the grub source from here and tried loading on my HP Z440 desktop. 
I have enabled the TPM security knob in my BIOS but i am seeing this error and my system refuses to Boot 

+++++++++++++++++++++++++
rustedGRUB2 loading 
Welcome to TrustedGRUB2!
TCG_HasgLogExtendEvent failed : 0x2 
Aborted. Press any key to exit

+++++++++++++++++++++=
Any ideas what am i doing wrong here. 
I looked the TCG PC spec the error number 0x2 seems to indicate that i got TCG_PC_LOGOVERFLOW 
it means insufficient memory to create log entry. What am i missing here 
my dmesg output when i boot without trusted grub shows this 

tpm_tis 00:09: 1.2 TPM (device-id 0x1A, rev-id 16)

**Comment by neusdan** [comment]
Strange. Never seen this before. Probably a bios bug. Are you running the latest version?

**Comment by amitlimaye** [comment]
I got the source from the git tree. 
I was thinking BIOS bug as well i am going to try the same thing on a different vendor server. 
The  TCG_PC_LOGOVERFLOW  made me think if i needed to configure something in my BIOS or TPM chip like carving out a region for logs in NVRAM before i try to boot with this. The BIOS has no further options beyond enabling and disabling the chip. (or making it hidden). All those things are set as HP asks me to

**Comment by neusdan** [comment]
Do you have the latest BIOS version installed?

**Comment by amitlimaye** [comment]
havent checked but i got this desktop from HP last week
will reach out to HP to check it

-SIGTERM
amit

Humanity's first sin was faith, Its first virtue doubt

**Comment by amitlimaye** [comment]
looks like my BIOS is a few versions old i have 2.14 the latest is 2.19

**Comment by Maxvior** [comment]
I have a similar issue, it does not work with version 1.4 and master. Try version 1.3, should work.

**Comment by neusdan** [comment]
Could you tell us what error exactly?

**Comment by johnwallace123** [comment]
@amitlimaye @white00black: Can you try the code from PR #55 and see if that resolves your issue?  It looks like there's a widespread bug in newer BIOSes that prevents appending to the TPM event log with certain calls.

**Comment by securitykernel** [comment]
Unfortunately, this project is deprecated and no longer maintained. I will be closing this issue.
