### ISSUE TITLE
How to verify if kernel and ramdisk are modified illegally

### ISSUE THREAD

**Issue by Maxvior** [Sirrix-AG/TrustedGRUB2#46]
In version 1.3 with debug info, I can see that hash values of kernel and ramdisk  are correct and have been written to PCR-10. However when I change kernel or ramdisk on purpose, the PCR-10 has been updated to a new value automatically and device still can boot successfully. I do not see the verification process to avoid the illegal change of kernel or ramdisk.

Am I wrong in somewhere?

**Comment by neusdan** [comment]
There is no such verification process. From the README:

> Since the TPM is passive, it has no direct ability to check if the integrity of bootloader (and the OS kernel/modules and so on) actually is correct. This can only be done indirectly by using the seal/unseal functions of the TPM (for details on this topic, you should have a look at the TCG specifications or on other documents describing TCG/TPM abilities).
