### ISSUE TITLE
Out-of-bounds read in luks.c

### ISSUE THREAD

**Issue by mike-joseph** [Sirrix-AG/TrustedGRUB2#6]
# Problem

The TCG code added to `grub-core/disk/luks.c` function `luks_recover_key()` introduced out-of-bounds memory access in its handling of the variables `secret` and `secretSize`.
# Details

Specifically, on `luks.c` _line 389 (master)_, `secret` is set to the contents of a disk file of arbitrary size while `secretSize` is set to `keysize`, a quantity unrelated to the length of the disk file. Further, on _line 398_, `secret` is set to the unsealed contents of a disk file but `secretSize` is not changed at all.

These circumstances result in the call to `grub_crypto_pbkdf2()` on _line 437_ passing a byte array `secret` with an incorrect length `secretSize`.  If the true length of `secret` is less than the value `keysize`, such as a disk file or sealed payload that is shorter than required, this will result in the GRUB crypto functions reading from the heap past the length of the `secret` byte array.  Since the functions are merely computing hashes and GRUB is running in real mode, this is unlikely to introduce a security vulnerability nor crash, but generally considered unsafe practice.

Moreover, in any case where the keyfile (or sealed key payload) is of a different size than the native key length in the LUKS header, this will result in incorrect hashing and decrypt failures.  In particular, there is no requirement that the keyfile be exactly the size of the native key length in LUKS, due to the PBKDF2 hashing.  I believe this to be the true cause of the problem in issue #5.
# Recommended Solution

`luks.c` _lines 388 - 389_ should be changed to:

```
    secret = (char*) keyFileBuf;
    secretSize = fileSize;
```

`luks.c` _line 398_ should be changed to:

```
        secret = (char*) unsealedKeyFile;
        secretSize = resultSize;
```

**Comment by neusdan** [comment]
Thanks for reporting and your nice write up :thumbsup:
I have applied your recommended changes.
