### ISSUE TITLE
Unable to install on MBR

### ISSUE THREAD

**Issue by stratoss** [Sirrix-AG/TrustedGRUB2#60]
Hi,

The normal grub2 is installing and running properly, but when I try to install TrustedGRUB2 I receive:

>sudo /opt/trustedgrub2/sbin/grub-install --directory=/opt/trustedgrub2/lib/grub/i386-pc/ /dev/sda
Installing for i386-pc platform.

>/opt/trustedgrub2/sbin/grub-install: warning: cannot open directory `/opt/trustedgrub2/share/locale': No such file or directory.

>/opt/trustedgrub2/sbin/grub-install: error: disk `lvm/sda1_crypt' not found.

sda1_crypt is the alias for the decrypted /dev/sda1 which is my boot partition.

I guess it is because of the /boot encryption, as /opt/trustedgrub2/sbin/grub-mkconfig is throwing the same error. My idea is to enter the luks password once, to decrypt the /boot partition, and then use TrustedGRUB2 with TPM to decrypt the other partitions. Is that possible at the moment?

**Comment by neusdan** [comment]
If this is still relevant for you, can you check if current master is still throwing this error?

**Comment by stratoss** [comment]
It works, thank you, @neusdan

**Comment by tahirahmad1985** [comment]
Hi stratoss, could you please help me and put some comments on issue 70

**Comment by tahirahmad1985** [comment]
Sorry, actually issue 72

**Comment by securitykernel** [comment]
Unfortunately, this project is deprecated and no longer maintained. I will be closing this issue.
