### ISSUE TITLE
TrustedGRUB2 hangs without errors

### ISSUE THREAD

**Issue by fchiacchiaretta** [Sirrix-AG/TrustedGRUB2#61]
Hi,
I built trustedgrub2 and installed it, no error when installing it on /dev/sda.
TPM is enabled but when I reboot my server after installation (Lenovo X3650 M5), I get stuck at:

```
TrustedGRUB2 loading.
Welcome to TrustedGRUB2!
```

/boot partition in not encrypted.
No errors are thrown even after waiting several minutes.

Is there a way to troubleshoot this issue?

**Comment by fchiacchiaretta** [comment]
I managed to compile with debug enabled, on reboot I get the following message:

```
TrustedGRUB2 loading.
Welcome to TrustedGRUB2!

measured module: terminal
SHA1 of buffer: _40-digits string_
```

**Comment by neusdan** [comment]
Seems to be related to #53. The changes in #55 probably solves this problem.

**Comment by fchiacchiaretta** [comment]
Thanks for pointing it out. Following [#55](https://github.com/Rohde-Schwarz-Cybersecurity/TrustedGRUB2/pull/55) and compiling with TGRUB_NOEVENTLOG flag the boot process goes on as expected.

Thanks for your support.
Should I close this issue or leave it open until [#55](https://github.com/Rohde-Schwarz-Cybersecurity/TrustedGRUB2/pull/55) is merged?

**Comment by neusdan** [comment]
Glad this works for you. You can leave it open.

**Comment by securitykernel** [comment]
Unfortunately, this project is deprecated and no longer maintained. I will be closing this issue.
