### ISSUE TITLE
Problem with two raid 

### ISSUE THREAD

**Issue by ghost** [Sirrix-AG/TrustedGRUB2#63]
I have two raid : sda with raid 1 and sdb2 with raid 5 . I have modified tpm-luks.conf for /dev/sda2 and sdb1 with index 1 and 2 . However i reboot the Pc , the application asks me the password on the volumes ... I don't understand ... Best regard

**Comment by neusdan** [comment]
Looks like this is a tpm-luks related question. I can only try to help with TrustedGRUB2 specific things. I don't use tpm-luks.

**Comment by securitykernel** [comment]
Unfortunately, this project is deprecated and no longer maintained. I will be closing this issue.
