### ISSUE TITLE
Tag release 1.5.0?

### ISSUE THREAD

**Issue by ddz** [Sirrix-AG/TrustedGRUB2#74]
The most recent commits to master brought in Grub 2.02 and [documented release 1.5.0 in the `Changelog.md`](https://github.com/Rohde-Schwarz-Cybersecurity/TrustedGRUB2/commit/b45ac44821605f4b69d784b4663d78f815fd1aa1). Should the current version of master be considered 1.5.0 and do you have plans to git tag a release of 1.5.0?

**Comment by securitykernel** [comment]
Unfortunately, this project is deprecated and no longer maintained. I will be closing this issue. However, see #82 for a recent release.
