### ISSUE TITLE
Can't compile TrustedGRUB2 with GCC 8

### ISSUE THREAD

**Issue by Marcel-Lambacher** [Sirrix-AG/TrustedGRUB2#77]
### Description
If I try to compile TrustedGRUB2 using make and gcc, I'll run into build errors.
### Current Behaviour
If I execute make, I'll get the following build error:
```
In file included from grub-core/disk/ldm.c:26:
./include/grub/gpt_partition.h:79:1: error: alignment 1 of ‘struct grub_gpt_partentry’ is less than 8 [-Werror=packed-not-aligned]
 } GRUB_PACKED;
 ^
```
### Expected Behaviour
I'm able to compile TrustedGRUB2 using make without any problems.
### System Informations
```
# gcc -v

Using built-in specs.
COLLECT_GCC=gcc
Thread model: posix
gcc version 8.1.1 20180712 (Red Hat 8.1.1-5) (GCC)
```
### Fix
I already created a pull request to fix this issue: #76

**Comment by securitykernel** [comment]
Unfortunately, this project is deprecated and no longer maintained. I will be closing this issue.
