### ISSUE TITLE
Should I change to ./configure --prefix=INSTALLDIR --target=x86_64 -with-platform=pc

### ISSUE THREAD

**Issue by BlazingForests** [Sirrix-AG/TrustedGRUB2#79]
Hi,
I am using debian 9.5,  also using BIOS, not UEFI, and TPM1.2 module
Should I change to 
./configure --prefix=INSTALLDIR --target=x86_64 -with-platform=pc

In readme.md file was
./configure --prefix=INSTALLDIR --target=i386 -with-platform=pc

**Comment by securitykernel** [comment]
Unfortunately, this project is deprecated and no longer maintained. I will be closing this issue.
