### ISSUE TITLE
show "TrustedGRUB2 TPM Error" when boot

### ISSUE THREAD

**Issue by BlazingForests** [Sirrix-AG/TrustedGRUB2#80]
Hi, guys, I am following https://github.com/fox-it/linux-luks-tpm-boot to setup FDE, but something wrong.

Detail ->  https://github.com/fox-it/linux-luks-tpm-boot/issues/22

Please help. THX.

**Comment by securitykernel** [comment]
Unfortunately, this project is deprecated and no longer maintained. I will be closing this issue.
