### ISSUE TITLE
Minimal BASH-like at boot, then what

### ISSUE THREAD

**Issue by lweingart** [Sirrix-AG/TrustedGRUB2#81]
Hi,
It appears that I installed TrustedGRUB2 with success. However, when I boot the computer gets stuck at the following screen, proposing a Minimal BASH-like line editor. What am I supposed to do next, to get my computer to automatically complete the boot process ?

Here is a picture of the mentioned screen

![trustedgrub2](https://user-images.githubusercontent.com/4840059/49284847-10dd2400-f496-11e8-9470-63fdd4519f40.jpg)

**Comment by securitykernel** [comment]
Unfortunately, this project is deprecated and no longer maintained. I will be closing this issue.
