### ISSUE TITLE
Grub Menu Edits still booting

### ISSUE THREAD

**Issue by SomeMuthaFunky** [Sirrix-AG/TrustedGRUB2#83]
I'm using TrustedGrub2 but edits to the menu at boot still allow the machine to boot which would allow an attack on the system. NVram is sealed etc. What am I doing wrong or am i misunderstanding its capabilities?

**Comment by Lyssers** [comment]
I have this same issue.

**Comment by securitykernel** [comment]
Unfortunately, this project is deprecated and no longer maintained. I will be closing this issue.
