### ISSUE TITLE
TrustedGrub2 stuck on boot

### ISSUE THREAD

**Issue by networkingana** [Sirrix-AG/TrustedGRUB2#86]
Hello

I installed TrustedGrub2 on CentOS 7 following the guide from the GitHub configuration.

The TrustedGrub2 is successfully installed but after installing it on /dev/sda and rebooting the system, the system is stuck on 
```
TrustedGrub2 loading
Welcome to TrustedGrub2!

measured module: terminal
SHA1 of buffer: <hash value>
```

I am trying to achieve sealing of TPM using the LUKS password on / partition, so when booting the system, the system does not prompt for LUKS password.

Thank you

**Comment by securitykernel** [comment]
Unfortunately, this project is deprecated and no longer maintained. I will be closing this issue.
